name: Build Kernel

on:
  workflow_dispatch:
jobs:
  create_tar:
    name: Create kernel tar
    runs-on: ubuntu-latest

    steps:
      - name: Pack kernel
        run: |
             wget https://github.com/mj22226/linux/archive/refs/tags/v6.6.60-rc1.tar.gz
             tar -xf v6.6.60-rc1.tar.gz --one-top-level=linux-6.6.60
             tar -c linux-6.6.60 | xz > linux-6.6.60.tar.xz
             sha256sum *.xz > sha256sum

      - name: Release build artifacts
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          prerelease: false
          name: kernel v6.6
          tag: v6.6
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
                    *.xz
                    sha256sum
