name: ipq40 images
on:
   workflow_dispatch:
jobs:
    build:
        name: ipq40 images
        runs-on: ubuntu-latest
        steps:
            - name: Maximize build space
              uses: easimon/maximize-build-space@master
              with:
                root-reserve-mb: 512
                swap-size-mb: 1024
                remove-dotnet: 'true'
                overprovision-lvm: 'true'
                remove-android: 'true'
                remove-haskell: 'true'
                remove-codeql: 'true'
                remove-docker-images: 'true'
            - name: checkout
              uses: actions/checkout@v4
            - name: Build
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cp -rf r3/* openwrt/
                cd openwrt
                wget https://github.com/mj22226/source/commit/b474cbc279d66a4604a30dc69630876db3e41604.patch
                git apply b474cbc279d66a4604a30dc69630876db3e41604.patch
                git apply 40.patch
                echo "src-git youtubeUnblock https://github.com/antnyfls/youtubeUnblock.git;openwrt" >> feeds.conf.default
                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                mv ipq40 .config
                make defconfig
                make download -j32
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                tar -czvf bin/targets/ipq40xx/generic/packages.tar.gz bin/targets/ipq40xx/generic/packages
                tar -czvf bin/targets/ipq40xx/generic/feeds-packages.tar.gz bin/packages
                rm -rf bin/targets/ipq40xx/generic/packages
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
            - name: Delete tag
              uses: ClementTsang/delete-tag-and-release@v0.4.0
              with:
                delete_release: true
                tag_name: ipq-40
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create release
              uses: ncipollo/release-action@v1.14.0
              with:
                allowUpdates: true
                name: IPQ40 Images ${{ env.D }}
                tag: ipq-40
                replacesArtifacts: true
                makeLatest: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/ipq40xx/generic/*
