name: bpi-r3 images
on:
  schedule:
    - cron: '30 19 * * *'

jobs:
    build:
        name: Build BPI-R3 Images
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Build
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cp -rf r3/* openwrt/
                cd openwrt
                git apply 0001-bpi-r3.patch
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd feeds/luci
                wget https://gist.githubusercontent.com/mj22226/f6db007367a22a31f9cb1c109a032b45/raw/be368c4f1605f652a001d81548c3a3e14adf6cb7/luci-app-diskman.patch
                git apply luci-app-diskman.patch
                cd -
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd
                sed -i "45s/<255 96 0>/<0 96 255>/" target/linux/mediatek/files-5.15/arch/arm64/boot/dts/mediatek/mt7986a-bananapi-bpi-r3.dts
                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                mv r3 .config
                make defconfig
                make download -j32
                make tools/install -j$(nproc)
                make toolchain/install -j$(nproc)
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                rm -rf bin/targets/mediatek/filogic/packages
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
            - name: Create release
              uses: ncipollo/release-action@v1.12.0
              with:
                allowUpdates: true
                name: BPI-R3 Images ${{ env.D }}
                tag: r3-${{ env.D }}
                replacesArtifacts: true
                prerelease: false
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/mediatek/filogic/*
