name: bpi-r3 images
on:
  schedule:
    - cron: '00 01 * * *'

jobs:
    build:
        name: Build BPI-R3 Images
        runs-on: ubuntu-latest
        steps:
            - name: Maximize build space
              uses: easimon/maximize-build-space@master
              with:
                root-reserve-mb: 512
                swap-size-mb: 1024
                remove-dotnet: 'true'
                overprovision-lvm: 'true'
                remove-android: 'true'
                remove-haskell: 'true'
                remove-codeql: 'true'
                remove-docker-images: 'true'
            - name: checkout
              uses: actions/checkout@v4
            - name: Build
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cp -rf r3/* openwrt/
                cd openwrt
                wget https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/llvm-bpf-15.0.7.Linux-x86_64.tar.xz
                tar -xvf llvm-bpf-15.0.7.Linux-x86_64.tar.xz
                git apply 0001-bpi-r3.patch
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd feeds/luci
                wget https://gist.githubusercontent.com/mj22226/363cefecd314e45b49d8eafff8473fcf/raw/69b47c9a972e15056f94870d76d93a5146893f99/01-diskman.patch
                git apply 01-diskman.patch
                cd -
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd
                sed -i "45s/<255 96 0>/<0 96 255>/" target/linux/mediatek/files-5.15/arch/arm64/boot/dts/mediatek/mt7986a-bananapi-bpi-r3.dts
                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                rm -rf files/etc/opkg
                mv r3 .config
                make defconfig
                make download -j32
                make tools/install -j$(nproc)
                make toolchain/install -j$(nproc)
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                rm -rf bin/targets/mediatek/filogic/packages
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
            - name: Create release
              uses: ncipollo/release-action@v1.14.0
              with:
                allowUpdates: true
                name: BPI-R3 Images ${{ env.D }}
                tag: r3-${{ env.D }}
                replacesArtifacts: true
                prerelease: false
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/mediatek/filogic/*
