name: bpi-r3 v1.2-rc images
on:
   workflow_dispatch:
   schedule:
    - cron: '45 9 * * *'
jobs:
    build:
        name: Build BPI-R3 v1.2-rc Images
        runs-on: ubuntu-latest
        steps:
            - name: Maximize build space
              uses: easimon/maximize-build-space@master
              with:
                root-reserve-mb: 512
                swap-size-mb: 1024
                remove-dotnet: 'true'
                overprovision-lvm: 'true'
                remove-android: 'true'
                remove-haskell: 'true'
                remove-codeql: 'true'
                remove-docker-images: 'true'
            - name: checkout
              uses: actions/checkout@v4
            - name: Build
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cp -rf r3/* openwrt/
                cd openwrt
                wget https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/llvm-bpf-18.1.7.Linux-x86_64.tar.zst
                tar -xvf llvm-bpf-18.1.7.Linux-x86_64.tar.zst
                wget https://github.com/mj22226/openwrt/commit/848e171336e93686c886333ef978537b35c090d6.patch
                wget https://github.com/mj22226/openwrt/commit/cd3b961bd2bccd10f385fa94bd55285113f27da0.patch
                wget https://github.com/mj22226/openwrt/commit/8b9b1723955a93498ed6df58f3b22a92fb991aaa.patch
                wget https://github.com/mj22226/openwrt/commit/0964b12f6d827e73a0f96ef118d81f4d4263bc46.patch
                git apply 0001-bpi-r31.patch
                git apply 848e171336e93686c886333ef978537b35c090d6.patch
                git apply cd3b961bd2bccd10f385fa94bd55285113f27da0.patch
                git apply 8b9b1723955a93498ed6df58f3b22a92fb991aaa.patch
                git apply 0964b12f6d827e73a0f96ef118d81f4d4263bc46.patch
                echo "src-git youtubeUnblock https://github.com/antnyfls/youtubeUnblock.git;openwrt" >> feeds.conf.default
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd feeds/luci
                wget https://gist.githubusercontent.com/mj22226/363cefecd314e45b49d8eafff8473fcf/raw/69b47c9a972e15056f94870d76d93a5146893f99/01-diskman.patch
                wget https://github.com/openwrt/luci/commit/10319bbcc4fa50e29e18ecc0b29c8a26124604f2.patch
                git apply 01-diskman.patch
                git apply 10319bbcc4fa50e29e18ecc0b29c8a26124604f2.patch
                cd -
                cd  feeds/packages
                wget https://gist.githubusercontent.com/mj22226/351f11e66f08f06e37a985719a31ddb4/raw/b35ba7a3aac1949bd6bbeaad065a0a93dc3c34f0/01-cpu.patch
                wget https://gist.githubusercontent.com/mj22226/b66f5c1bd5fc7e1cb3cf2c690b5dbd5a/raw/b955e726cbb0948d932c8d6143229ad604320149/20-lxc.patch
                git apply 01-cpu.patch
                git apply 20-lxc.patch
                cd -
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd
                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                mkdir -p files/www/repo
                mv r31 .config
                make defconfig
                make download -j32
                make -j$(nproc) 'IGNORE_ERRORS=n m' || true
                tar -czvf bin/targets/mediatek/filogic/packages.tar.gz bin/targets/mediatek/filogic/packages || true
                tar -czvf bin/targets/mediatek/filogic/feeds-packages.tar.gz bin/packages || true
                tar -czvf bin/targets/mediatek/filogic/logs.tar.gz logs
                rm -rf bin/targets/mediatek/filogic/packages || true
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
            - name: Delete tag
              uses: ClementTsang/delete-tag-and-release@v0.4.0
              with:
                delete_release: true
                tag_name: v1.2-rc
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create release
              uses: ncipollo/release-action@v1.14.0
              with:
                allowUpdates: true
                name: BPI-R3 v1.2-rc Images ${{ env.D }}
                tag: v1.2-rc
                replacesArtifacts: true
                makeLatest: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/mediatek/filogic/*
