name: bpi-r3 v1.2 images
on:
   workflow_dispatch:
   schedule:
    - cron: '01 08 * * *'
jobs:
    build:
        name: Build BPI-R3 v1.2 Images
        runs-on: ubuntu-latest
        steps:
            - name: Maximize build space
              uses: easimon/maximize-build-space@master
              with:
                root-reserve-mb: 512
                swap-size-mb: 1024
                remove-dotnet: 'true'
                overprovision-lvm: 'true'
                remove-android: 'true'
                remove-haskell: 'true'
                remove-codeql: 'true'
                remove-docker-images: 'true'
            - name: checkout
              uses: actions/checkout@v4
            - name: Build
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cp -rf r3/* openwrt/
                cd openwrt
                wget https://github.com/mj22226/source/commit/e60a6ff982857a7703b3d6dc6b0a734a85098fec.patch
                git apply e60a6ff982857a7703b3d6dc6b0a734a85098fec.patch
                tar -xvf llvm-bpf-18.1.7.Linux-x86_64.tar.zst
                git apply 0001-bpi-r31.patch
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd feeds/luci
                wget https://gist.githubusercontent.com/mj22226/363cefecd314e45b49d8eafff8473fcf/raw/69b47c9a972e15056f94870d76d93a5146893f99/01-diskman.patch
                git apply 01-diskman.patch
                cd -
                cd  feeds/packages
                wget https://gist.githubusercontent.com/mj22226/351f11e66f08f06e37a985719a31ddb4/raw/b35ba7a3aac1949bd6bbeaad065a0a93dc3c34f0/01-cpu.patch
                wget https://gist.githubusercontent.com/mj22226/b66f5c1bd5fc7e1cb3cf2c690b5dbd5a/raw/b955e726cbb0948d932c8d6143229ad604320149/20-lxc.patch
                wget https://github.com/mj22226/packages/commit/3ac93f1646a33162b6bb6bdbf96e0a28a5ca76ae.patch
                git apply 01-cpu.patch
                git apply 20-lxc.patch
                git apply 3ac93f1646a33162b6bb6bdbf96e0a28a5ca76ae.patch
                cd -
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd
                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                mkdir -p files/www/repo
                mv r31 .config
                make defconfig
                make download -j32
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                tar -czvf bin/targets/mediatek/filogic/packages.tar.gz bin/targets/mediatek/filogic/packages
                rm -rf bin/targets/mediatek/filogic/packages
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
            - name: Delete tag
              uses: ClementTsang/delete-tag-and-release@v0.4.0
              with:
                delete_release: true
                tag_name: v1.2
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create release
              uses: ncipollo/release-action@v1.14.0
              with:
                allowUpdates: true
                name: BPI-R3 v1.2 Images ${{ env.D }}
                tag: v1.2
                replacesArtifacts: true
                makeLatest: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/mediatek/filogic/*
