name: wndr3800 images
on:
   workflow_dispatch:
jobs:
    build:
        name: Build wndr3800 Images
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Build
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cp -rf r3/* openwrt/
                cd openwrt
                wget https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/llvm-bpf-18.1.7.Linux-x86_64.tar.zst
                tar -xvf llvm-bpf-18.1.7.Linux-x86_64.tar.zst
                wget https://github.com/mj22226/openwrt/commit/fc597c22cf2c6bca49523e4fd0caa51a38d40275.patch
                git apply fc597c22cf2c6bca49523e4fd0caa51a38d40275.patch
                wget https://github.com/mj22226/openwrt/commit/c17ad496131b0ee1614ddd453b4b7b64a161dbd1.patch
                wget https://github.com/mj22226/openwrt/commit/659ed09bdaf47f47b6d98e7690cadc59ba47da5f.patch
                wget https://github.com/mj22226/openwrt/commit/9d62749914fd98695d387e7a38f4cae9fee6a221.patch
                wget https://github.com/mj22226/openwrt/commit/354308d13dccd1d654704abf627aa5da2d9907e3.patch
                git apply 0001-bpi-r31.patch
                git apply c17ad496131b0ee1614ddd453b4b7b64a161dbd1.patch
                git apply 659ed09bdaf47f47b6d98e7690cadc59ba47da5f.patch
                git apply 9d62749914fd98695d387e7a38f4cae9fee6a221.patch
                git apply 354308d13dccd1d654704abf627aa5da2d9907e3.patch
                git apply 38.patch
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                mv w3800 .config
                make defconfig
                make download -j32
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                rm -rf bin/targets/ath79/generic/packages
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
            - name: Delete tag
              uses: ClementTsang/delete-tag-and-release@v0.4.0
              with:
                delete_release: true
                tag_name: w3800
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create release
              uses: ncipollo/release-action@v1.14.0
              with:
                allowUpdates: true
                name: WRND3800 Images ${{ env.D }}
                tag: w3800
                replacesArtifacts: true
                makeLatest: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/ath79/generic/*
